print("what is your name?")
name=input()
print("what is your organization?")
org=input() 
print("what is your contact?")
contact=input()
print("what is your access?")
access=input()
print("|--------------------------------------|")
print("|------BCH Software Terminal System----|")
print("|--------------------------------------|")
print("|ATTENDEE: " + name.ljust(28) + "|" ) 
print("|Organization: " + org.ljust(24) + "|" ) 
print("|Contact: " + contact.ljust(29) + "|" ) 
print("|access: " + access.ljust(30) + "|" ) 
print("|------BCH Software Terminal System----|")